
services:
  db:
    image: mongo:4
    container_name: tutihair_db
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - ./tutiEcommerceDB:/data/db    
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
      MONGO_INITDB_DATABASE: admin
    networks:
      - app-network

  backend:
    build: .
    container_name: tutihair_backend
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db
    networks:
      - app-network

networks:
  app-network:
    external: true
