services:
  db:
    image: mongo:4
    container_name: tutihair_db
    restart: always
    volumes:
      - ./tutiEcommerceDB:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
      MONGO_INITDB_DATABASE: admin
    deploy:
      resources:
        limits:
          cpus: "0.7"
          memory: 600M
    networks:
      - app-network

  backend:
    build: .
    container_name: tutihair_backend
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - ./backend:/app
    depends_on:
      - db
    deploy:
      resources:
        limits:
          cpus: "0.6"
          memory: 500M
    networks:
      - app-network

networks:
  app-network:
    external: true
